# Generated by Django 3.2.4 on 2021-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20210629_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='responsible',
        ),
        migrations.AddField(
            model_name='course',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='courses', to='education.Mentor', verbose_name='Преподаватели'),
        ),
    ]
